export const GET_GROUP = 'get all the groups'
export const GET_GROUP_DETAILS = 'get the details of the group'
export const GET_FILTERED_MEMBERS = 'filters the members'
export const UPDATE_FAMILY_MEMBERS = 'updating the members in family'
export const ADDED_GROUP = 'added a new group'
export const RESET_SETTINGS = 'reset the options'